// Initialize Ink Engine
let story;
const storyContainer = document.querySelector('#story-text');
const choicesContainer = document.querySelector('#choices-container');
const imageElement = document.querySelector('#scene-image');

// Load the compiled JSON version of your .ink file
fetch('adventure.json')
    .then(response => response.json())
    .then(storyJson => {
        story = new inkjs.Story(storyJson);
        continueStory();
    });

function continueStory() {
    let content = "";
    
    // 1. Clear UI
    storyContainer.innerHTML = "";
    choicesContainer.innerHTML = "";

    // 2. Read all text until choices or end
    while (story.canContinue) {
        var paragraphText = story.Continue();
        handleTags(story.currentTags);
        content += `<p>${paragraphText}</p>`;       
    }

    storyContainer.innerHTML = content;

    // 4. Render Choices
    story.currentChoices.forEach(choice => {
        let btn = document.createElement('button');
        btn.innerText = choice.text;
        btn.classList.add('choice-btn');
        btn.onclick = () => {
            story.ChooseChoiceIndex(choice.index);
            continueStory();
        };
        choicesContainer.appendChild(btn);
    });
}

// Function to handle tags generated by InkSmith
function handleTags(tags) {
    var imageContainer = document.getElementById('story-image'); // You need this DIV in HTML
    
    if (tags) {
        for (var i = 0; i < tags.length; i++) {
            var tag = tags[i].trim();
            
            // Look for "IMAGE: filename"
            if (tag.startsWith("IMAGE:")) {
                var imageName = tag.split(":")[1].trim();
                // Update the image source (assuming assets are in relative folder)
                imageContainer.src = "assets/" + imageName + ".png";
                imageContainer.style.display = "block";
            }
        }
    }
}